# Generated by Django 4.0.6 on 2022-08-06 00:44

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('rate', models.IntegerField()),
                ('approved', models.BooleanField(default=False)),
                ('status', models.CharField(default='ready', max_length=30)),
                ('company_scale', models.TextField()),
                ('comapny_tips', models.TextField()),
                ('job_info', models.TextField()),
                ('created_at', models.DateTimeField(default=datetime.datetime(2022, 8, 5, 17, 44, 37, 540012))),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
