# Generated by Django 4.0.6 on 2022-08-06 02:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='comapny_tips',
            new_name='company_tips',
        ),
        migrations.AlterField(
            model_name='job',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 5, 19, 14, 43, 29465)),
        ),
    ]
